# Generated by Django 4.0.3 on 2022-04-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_marker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
