# Generated by Django 4.0.3 on 2022-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_marker', '0004_alter_marker_lat_alter_marker_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lng',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
