# Generated by Django 4.0.3 on 2022-04-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_customer_user_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
