# Generated by Django 4.0.3 on 2022-04-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_businessevent_user_personalevent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessevent',
            old_name='end_event',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='businessevent',
            old_name='start_event',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='personalevent',
            old_name='end_event',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='personalevent',
            old_name='start_event',
            new_name='start',
        ),
    ]
