# Generated by Django 4.0.3 on 2022-04-18 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
